ACTION_TYPES =
	ICOF:
		ADD_ICO_CELL: "ADD_ICO_CELL"
		REMOVE_ICO_CELL: "REMOVE_ICO_CELL"
		INDENT_ICO_CELL: "INDENT_ICO_CELL"
		FOCUS_NEXT_CELL: "FOCUS_NEXT_CELL"
		FOCUS_PREVIOUS_CELL: "FOCUS_PREVIOUS_CELL"
		TOGGLE_FOLD_ON_CELL: "TOGGLE_FOLD_ON_CELL"
		TOGGLE_ICOF_ACTIVE: "TOGGLE_ICOF_ACTIVE"
	CANVAS:
		ADD_ICOF: "ADD_ICOF"
		REMOVE_ICOF: "REMOVE_ICOF"



module.exports = ACTION_TYPES